### ISSUE TITLE
Address a few notable gaps in avoid-unneccessary-command eslint rule for a few common usage patterns

### ISSUE THREAD

**Issue by rlandav** [Mojang/minecraft-scripting-libraries#12]
A few other scenarios need to be handled by the eslint rule which are common

1. `runCommand` where there is no leading `/` for the command
1. `runCommandAsync` immediately await'ed on
1. `runCommandAsync` where the promise is assigned to a local variable

**Comment by SBLMikeDemone** [comment]
These additional cases were implemented with https://github.com/Mojang/minecraft-scripting-libraries/pull/21
