### ISSUE TITLE
Linting for set block checks for the incorrect casing

### ISSUE THREAD

**Issue by ThomasOrs** [Mojang/minecraft-scripting-libraries#17]
# Summary
The check for `/setblock` looks for `/setBlock`, which is not the standardised casing for commands in Minecraft. Reference documentation does list the correct casing.

# To test
- Create a project with eslint & the command linting plugin enabled
- Create a `main.ts` with `world.getDimension("overworld").runCommand("/setBlock 0 0 0 minecraft:air");`
- Run linting
- Confirm that you get a warning for `The /setBlock command can be fully replaced with the Block.setPermutation api in the @minecraft/server module`
- Change the command to `/setblock` and rerun lint
- Confirm that no lining error occurs

**Comment by rlandav** [comment]
Thanks for filing the issue! I'll take a look at the PR with the proposed fix.

I do think a better long term would be just to make the command comparison itself case insensitive, but i'll file that issue myself as a further improvement.

**Comment by ThomasOrs** [comment]
I meant to add that in the PR as a mid to long term suggestion but forgot!
